### PR TITLE
MVP version of the to-do list project 

### PR DESCRIPTION
**Pull request by ozovalihasan**
Please review the code for the javascript to-do list project. In this project, we:

- built task and project objects.
- added functions to add any project, add/delete/edit ant task.
- added the functions to display forms to create a project and create/update a task.
- added local storage for permanent project storage.
- separated our application logic from DOM-related stuff.

Thanks for reviewing.
Hasan and Somoye

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @ozovalihasan and @somoye123 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Make it easy for a user to switch between projects and its tasks
- [ ] You can make the scripts even better, refer the code below
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```
### Make the changes and submit for another code review. Good luck!
- Happy coding!

By Raymond
Slack @iamraymond

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### You have done well but one issue is still pending:-
- [x] If a user selects a project, all its tasks should be shown
### Make the change and submit for another code review. Good luck.
- Happy coding!

**Comment by somoye123** [comment]
> ### You have done well but one issue is still pending:-
> * [x]  If a user selects a project, all its tasks should be shown
> 
> ### Make the change and submit for another code review. Good luck.
> * Happy coding!

this is actually the case as tasks for the specific project selected is what get shown

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You got it right this time, the project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Comment by ozovalihasan** [comment]
Thanks, @rOluochKe for your review.

**Pull request merged**
